name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn install --frozen-lockfile
    - run: yarn test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      id: semver
      with:
        semver: '2.3.4-alpha.5'
        zero_pad: 3
    - run: echo "Output is ${{ steps.semver.outputs.integer }}"
